const PE = process.env.REACT_APP_PUBLIC_FOLDER
export const Users = [
    {
        id: 1,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Nikesh Pyakurel",
    },
    {
        id: 2,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Sulav Paudel",
    },
    {
        id: 3,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Rubin Moktan",
    },
    {
        id: 4,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Rahul Khanal",
    },
    {
        id: 5,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Bhawesh Kafle",
    },
    {
        id: 6,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Atul Verma",
    },
    {
        id: 7,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Nabin Maharjan",
    },
    {
        id: 8,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Anush Khadka",
    },
    {
        id: 9,
        profilePicture: `${PE}/person/1.jpg`,
        username: "Bhawana Rijal",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "post/1.jpeg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "post/1.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "post/1.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "post/1.jpeg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "post/1.jpeg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "post/1.jpeg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "post/1.jpeg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "post/1.jpeg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
];